core_homepage:
    path:     /
    defaults:
        _controller: CoreBundle:Home:index

core_contact:
    path: /contact
    defaults:
        _controller: CoreBundle:Home:contact

oc_platform:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix: /platform
